[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-prisma-provider"
  [plugins.inputs]
    path = "prisma/schema.prisma"      # caminho do schema.prisma
    varName = "DATABASE_URL"      # nome da variável de ambiente para o provider

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20.13.1"
  DATABASE_PROVIDER = "postgresql"    # define o provider como PostgreSQL para produção

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200


[dev]
  command = "next dev"
  targetPort = 3000
  port = 8888
  framework = "next"
